start-at-login = true
after-login-command = []
after-startup-command = [
    'exec-and-forget borders',
]
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 75
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
shift-cmd-j = 'focus left'
shift-cmd-k = 'focus down'
shift-cmd-l = 'focus up'
shift-cmd-semicolon = 'focus right'
ctrl-cmd-j = 'move left'
ctrl-cmd-k = 'move down'
ctrl-cmd-l = 'move up'
ctrl-cmd-semicolon = 'move right'
ctrl-cmd-minus = 'resize smart -50'
ctrl-cmd-equal = 'resize smart +50'
ctrl-cmd-comma = 'layout floating tiling'
ctrl-cmd-period = 'layout tiles horizontal vertical'
ctrl-cmd-slash = 'layout accordion horizontal vertical'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
# alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-b = 'workspace Browsing'
alt-c = 'workspace Code'
alt-m = 'workspace Music'
alt-s = 'workspace Slack'
shift-alt-1 = ['move-node-to-workspace 1']
shift-alt-2 = ['move-node-to-workspace 2']
# shift-alt-3 = ['move-node-to-workspace 3']
shift-alt-4 = ['move-node-to-workspace 4']
shift-alt-5 = ['move-node-to-workspace 5']
shift-alt-6 = ['move-node-to-workspace 6']
shift-alt-7 = ['move-node-to-workspace 7']
shift-alt-8 = ['move-node-to-workspace 8']
shift-alt-9 = ['move-node-to-workspace 9']
shift-alt-b = ['move-node-to-workspace Browsing']
shift-alt-c = ['move-node-to-workspace Code']
shift-alt-m = ['move-node-to-workspace Music']
shift-alt-s = ['move-node-to-workspace Slack']
shift-cmd-enter = 'mode service'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace Browsing'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace Browsing'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace Browsing'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace Code'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace Slack'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace Music'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace Music'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.googlecode.munki.ManagedSoftwareCenter'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.jamfsoftware.selfservice.mac'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.PairedDevices'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ScreenSharing'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'io.zsa.keymapp'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.pokemon.pokemontcgl'
run = 'layout floating'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']                # reset layout
backspace = ['close-all-windows-but-current', 'mode main']