#!/usr/bin/env bash

# Configure compact tab layout in Safari
defaults write com.apple.Safari ShowStandaloneTabBar -bool false 

# Set the icon size of Dock items to 48 pixels
defaults write com.apple.dock tilesize -int 48

# Set the Dock to auto-hide
defaults write com.apple.dock autohide -bool true

# Disable recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Wipe all default icons from the Dock
defaults write com.apple.dock persistent-apps -array

# Disable rearrange spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Enable group apps by application in Mission Control
defaults write com.apple.dock expose-group-apps -bool true 

# Disable mission control with window drag
defaults write com.apple.dock enterMissionControlByTopWindowDrag -bool false

# Disable Displays have separate spaces
defaults write com.apple.spaces spans-displays -bool true

# Ensure save dialogues expand by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Disable iCloud save panel
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Set sidebar item size to small
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# Set key repeat rate to fast
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Enable ctrl-cmd window dragging
defaults write NSGlobalDomain NSWindowShouldDragOnGesture -bool true

# Show item info near icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Show item info to the right of the icons on the desktop
/usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Enable snap-to-grid for icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy kind" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy kind" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy kind" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Increase the size of icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 48" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 48" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 48" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Set the text size for icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:textSize 11" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:textSize 11" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:textSize 11" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:ListViewSettings:textSize 11" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:textSize 11" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Set the sort method for icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:sortColumn kind" "${HOME}/Library/Preferences/com.apple.finder.plist"
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:ListViewSettings:sortColumn kind" "${HOME}/Library/Preferences/com.apple.finder.plist"

# Show items on the desktop
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Set the new window target to the home directory
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Spawn Finder in windows instead of tabs
defaults write com.apple.finder FinderSpawnTab -bool false

# Set the search scope to the current folder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Set the sort settings to put folders first
defaults write com.apple.finder _FXSortFoldersFirst -bool true
defaults write com.apple.finder _FXSortFoldersFirstOnDesktop -bool true

# Disable Finder recent tags
defaults write com.apple.finder ShowRecentTags -bool false

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder
chflags nohidden "${HOME}/Library"

# Setup Touch ID for sudo
sudo tee /etc/pam.d/sudo_local <<EOF
auth       sufficient     pam_tid.so
EOF
sudo chown root:wheel /etc/pam.d/sudo_local
sudo chmod 444 /etc/pam.d/sudo_local

# Restart things
for app in \
	"cfprefsd" \
	"SystemUIServer" \
	"Dock" \
	"Finder"; do
	killall "${app}" &> /dev/null
done

# Other apps
defaults write cc.ffitch.shottr alwaysOnTop -bool true
defaults write cc.ffitch.shottr areaCaptureMode -string "editor"
defaults write cc.ffitch.shottr copyOnEsc -bool false
defaults write cc.ffitch.shottr defaultFolder -string "~/Desktop"
defaults write cc.ffitch.shottr notificationType -string none
defaults write cc.ffitch.shottr saveOnEsc -bool true